# Copyright (C) Pipin Fitriadi - All Rights Reserved

# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Pipin Fitriadi <pipinfitriadi@gmail.com>, 28 August 2024

include:
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/jds@$CI_COMMIT_SHA
stages: [Test, Release, Deploy]
Ensure Job Added:
  stage: Test
  image: badouralix/curl-jq
  script:
    - |
      route="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/jobs"
      count=`curl --silent "$route" | jq 'map(select(.name | contains("CI/CD Catalog"))) | length'`
      if [ "$count" != "1" ]; then
        exit 1; else
        echo "Component Job present"
      fi
    # - |
    #   route=https://gitlab.com/api/v4/projects/61204183/pipelines/1439641712/jobs
    #   count=`curl --silent "$route" | jq 'map(select(.name | contains("CI/CD Catalog"))) | length'`
    #   if [ "$count" != "1" ]; then
    #     exit 1; else
    #     echo "Component Job present"
    #   fi
CI/CD Catalog:
  stage: Release
  rules:
    - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release [$CI_PROJECT_PATH@$CI_COMMIT_TAG](https://gitlab.com/explore/catalog/$CI_PROJECT_PATH) components to CI/CD Catalog"
