# Copyright (C) Pipin Fitriadi - All Rights Reserved

# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Pipin Fitriadi <pipinfitriadi@gmail.com>, 28 August 2024

stages:
  - Test
Code Quality:
  stage: Test
  image: pipelinecomponents/flake8
  variables:
    PIP_ROOT_USER_ACTION: ignore
  script:
    - pip install --upgrade pip
    - pip install flake8-bandit flake8-black flake8-bugbear flake8-isort
    - flake8
